import { Watches, Bicycles, Toys } from "../../../src/assets/images";

export const offerCardData = [
  {
    title: "Watches",
    image: Watches,
    description: "Silver watch with black strap",
    location: "Berlin",
    data: "31.05.2024",
    typeOffer: "Type offer",
    is_active: true,
    is_free: true,
    start_price: null,
    step: null,
    win_bid: null,
  },
  {
    title: "Bicycle",
    image: Bicycles,
    description: "Silver Bicycle with 18 speeds",
    location: "Munich",
    data: "31.05.2024",
    typeOffer: "Type offer",
    is_active: true,
    is_free: true,
    start_price: 100,
    step: 10,
    win_bid: null,
  },
  {
    title: "Toy",
    image: Toys,
    description: "Logic development toy for kids",
    location: "Hamburg",
    data: "31.05.2024",
    typeOffer: "Type offer",
    is_active: true,
    is_free: false,
    start_price: 50,
    step: 10,
    win_bid: 60,
  },
];
