name: Deploy frontent on https://second-life.space

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v4
    
        - name: Use Node.js 16
          uses: actions/setup-node@v2
          with:
            node-version: '16'
          
        - name: 🔨 Build Project
          run: |
            npm install
            npm run build:dev
        
        - name: 📂 Sync files
          uses: SamKirkland/FTP-Deploy-Action@v4.3.5
          with:
            server: ychepel.ftp.tools
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            protocol: ftps
            local-dir: ./build/
